config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'dante', to: 'pages#dante', as: 'dante'
  root 'pages#index'
  get 'username', to: 'pages#username', as: 'username'

  get 'username', to: 'pages#username', as: 'username'

  get 'sti4o', to: 'pages#sti4o', as: 'sti4o'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end


  def dante

  end

  def sti4o

  end

  def username
  end

  def mfrkzzmn

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamCollab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/TheKelso91.html.erb
<h1>Kelsey Evans<h1>

<p>University of Memphis student</p>
<ul>
    <li>Computer Science major</li>
    <li>Graduating in May 2025</li>
</ul>
<p>FedEx employee</p>
<ul>
    <li>Lead Production Supervisor</li>
    <li>Working for FedEx for 12 years</li>
</ul>
<p>Husky owner</p>

app/views/pages/dante.html.erb
<h1>Quick Intro</h1>
<p>Hello my name is Dante Donaldson and I am a computer science student and this is my page for sa19.</p>

app/views/pages/index.html.erb
<h1>Hello, My name is Farukuzzaman, I am majoring CS.</h1>
<P>I like to read the history and play soccer.</p>
<ul>
    <li><%= link_to 'mfrkzzmn', username_path %></li>

</ul>

app/views/pages/sti4o.html.erb
<h1> Stilyan's Page<h1>

<p> This is my page, as requested in the assingment. </p>

<p> I am a senior at the University of Memphis, majoring in Computer Science. </p>

app/views/pages/thekelso91.html.erb
<h1>Kelsey Evans<h1>

<p>University of Memphis student</p>
<ul>
    <li>Computer Science major</li>
    <li>Graduating in May 2025</li>
</ul>
<p>FedEx employee</p>
<ul>
    <li>Lead Production Supervisor</li>
    <li>Working for FedEx for 12 years</li>
</ul>
<p>Husky owner</p>

app/views/pages/username.html.erb
<h1>Kelsey Evans<h1>

<p>University of Memphis student</p>
<ul>
    <li>Computer Science major</li>
    <li>Graduating in May 2025</li>
</ul>
<p>FedEx employee</p>
<ul>
    <li>Lead Production Supervisor</li>
    <li>Working for FedEx for 12 years</li>
</ul>
<p>Husky owner</p>